/**
 * API: /api/probe
 *
 * POST — запустить Probe Engine для конкурента (по ID или URL)
 * GET  — список последних probe-запусков
 *
 * Request body (POST):
 *   { competitorId: string }  — для существующего конкурента
 *   { url: string }            — для нового URL (создаёт конкурента на лету)
 *
 * Response (POST):
 *   201 { probeResult: ProbeResult, specYaml: string, competitorId: string }
 *   400 { error: '...' }
 *   500 { error: '...' }
 */

import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { logger } from '@/lib/logger'
import { loadConfig } from '@/lib/config'
import { assertPublicHttpUrl, UnsafeUrlError } from '@/lib/security/url-policy'
import { getProbeEngine } from '@/scraper/strategies/probe-engine'

export const dynamic = 'force-dynamic'
export const maxDuration = 120 // probe может занять до 2 минут

interface ProbeRequestBody {
  competitorId?: string
  url?: string
  region?: string
}

export async function POST(req: NextRequest) {
  try {
    const body: ProbeRequestBody = await req.json()
    const { competitorId, url, region } = body

    if (!competitorId && !url) {
      return NextResponse.json(
        { error: 'Either competitorId or url is required' },
        { status: 400 }
      )
    }

    const targetRegion = region ?? loadConfig().TARGET_REGION
    const log = logger.child({ module: 'api/probe', region: targetRegion })

    // Найти или создать конкурента
    let competitor
    if (competitorId) {
      competitor = await db.competitor.findUnique({ where: { id: competitorId } })
      if (!competitor) {
        return NextResponse.json({ error: 'Competitor not found' }, { status: 404 })
      }
    } else if (url) {
      let normalizedUrl: string
      try {
        normalizedUrl = (await assertPublicHttpUrl(url)).origin
      } catch (e) {
        const message = e instanceof UnsafeUrlError ? e.message : 'Invalid URL'
        return NextResponse.json({ error: message }, { status: 400 })
      }

      // Найти или создать
      competitor = await db.competitor.findFirst({
        where: { OR: [{ baseUrl: normalizedUrl }, { baseUrl: `${normalizedUrl}/` }] },
      })
      if (!competitor) {
        const hostname = new URL(normalizedUrl).hostname.replace(/^www\./, '')
        competitor = await db.competitor.create({
          data: {
            name: hostname,
            baseUrl: normalizedUrl,
            status: 'probing',
          },
        })
        log.info({ competitorId: competitor.id, url: normalizedUrl }, 'Competitor created for probe')
      }
    }

    if (!competitor) {
      return NextResponse.json({ error: 'Failed to resolve competitor' }, { status: 500 })
    }

    // Обновить статус
    await db.competitor.update({
      where: { id: competitor.id },
      data: { status: 'probing' },
    })

    log.info({ competitorId: competitor.id, baseUrl: competitor.baseUrl }, 'Starting probe')

    // Запустить Probe Engine
    const probeEngine = getProbeEngine()
    const probeResult = await probeEngine.probe({
      baseUrl: competitor.baseUrl,
      region: targetRegion,
      sampleSize: 5,
      skipVLM: true,
    })

    // Сгенерировать spec.yaml
    const specYaml = await probeEngine.generateSpec(probeResult)

    // Сохранить ProbeResult в БД
    const probeResultRecord = await db.probeResult.create({
      data: {
        competitorId: competitor.id,
        probedAt: probeResult.probedAt,
        framework: probeResult.framework,
        isSSR: probeResult.isSSR,
        hasEmbeddedState: probeResult.hasEmbeddedState,
        hasSchemaOrg: probeResult.hasSchemaOrg,
        currencyFormat: probeResult.currencyFormat,
        tier: probeResult.tier,
        regionStrategy: probeResult.regionStrategy.type,
        sitemapUrlsCount: probeResult.sitemapUrls.length,
        priceUrlsCount: probeResult.totalUrlsDiscovered,
        confidenceScore: probeResult.confidenceScore,
        probeReportJson: JSON.stringify(probeResult),
      },
    })

    // Сохранить spec в БД
    const spec = await db.scrapeSpec.create({
      data: {
        competitorId: competitor.id,
        version: 1,
        specYaml,
        autoGenerated: true,
        confidence: probeResult.confidenceScore,
        status:
          probeResult.confidenceScore >= 70
            ? 'active'
            : probeResult.confidenceScore >= 40
              ? 'needs_review'
              : 'rejected',
        probeResultId: probeResultRecord.id,
        createdBy: 'probe-engine',
      },
    })

    // Обновить конкурента
    const updatedCompetitor = await db.competitor.update({
      where: { id: competitor.id },
      data: {
        status:
          probeResult.confidenceScore >= 70
            ? 'active'
            : probeResult.confidenceScore >= 40
              ? 'needs_review'
              : 'blocked',
        tier: probeResult.tier,
        regionStrategy: probeResult.regionStrategy.type,
        lastProbeAt: probeResult.probedAt,
        confidenceScore: probeResult.confidenceScore,
      },
    })

    log.info(
      {
        competitorId: competitor.id,
        tier: probeResult.tier,
        confidence: probeResult.confidenceScore,
        specId: spec.id,
        specStatus: spec.status,
      },
      'Probe completed'
    )

    return NextResponse.json(
      {
        competitorId: competitor.id,
        probeResult: {
          tier: probeResult.tier,
          tierReasoning: probeResult.tierReasoning,
          framework: probeResult.framework,
          isSSR: probeResult.isSSR,
          hasSchemaOrg: probeResult.hasSchemaOrg,
          hasEmbeddedState: probeResult.hasEmbeddedState,
          currencyFormat: probeResult.currencyFormat,
          regionStrategy: probeResult.regionStrategy,
          confidenceScore: probeResult.confidenceScore,
          totalUrlsDiscovered: probeResult.totalUrlsDiscovered,
          priceStrategies: probeResult.priceStrategies.map((s) => ({
            strategy: s.strategy,
            success: s.success,
            itemsExtracted: s.itemsExtracted,
            confidence: s.confidence,
          })),
          sampleUrls: probeResult.sampleUrls,
          homepageSize: probeResult.homepageSize,
        },
        specYaml,
        specId: spec.id,
        specStatus: spec.status,
        competitorStatus: updatedCompetitor.status,
      },
      { status: 201 }
    )
  } catch (e) {
    logger.error({ err: e, module: 'api/probe' }, 'Probe failed')
    return NextResponse.json(
      {
        error: 'Probe failed',
        details: (e as Error).message,
      },
      { status: 500 }
    )
  }
}

export async function GET() {
  try {
    const probeResults = await db.probeResult.findMany({
      take: 20,
      orderBy: { probedAt: 'desc' },
      include: {
        competitor: {
          select: { id: true, name: true, baseUrl: true },
        },
      },
    })

    return NextResponse.json({
      probeResults: probeResults.map((p) => ({
        id: p.id,
        competitorId: p.competitorId,
        competitorName: p.competitor.name,
        baseUrl: p.competitor.baseUrl,
        probedAt: p.probedAt,
        tier: p.tier,
        framework: p.framework,
        regionStrategy: p.regionStrategy,
        confidenceScore: p.confidenceScore,
        sitemapUrlsCount: p.sitemapUrlsCount,
        priceUrlsCount: p.priceUrlsCount,
      })),
      total: probeResults.length,
    })
  } catch (e) {
    logger.error({ err: e, module: 'api/probe' }, 'Failed to list probe results')
    return NextResponse.json(
      { error: 'Failed to fetch probe results' },
      { status: 500 }
    )
  }
}
